data:extend({
  {
    type = "fluid",
    name = "pod-health",
    icon_size = 32,
    auto_barrel = false,
    icon = "__life-pods__/graphics/heart.png",
    flags = {"hidden"},
    stack_size= 600,
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=1, g=0, b=0},
    flow_color = {r=1, g=0, b=0},
    max_temperature = 100,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-b[pod]",
    subgroup = "intermediate-product",
  },
})